- README.md
Adding a comment for reference.
> changed the README.md file to add subheader

- README.md
Added the downloaded file for config from CircleCI, need to configure and add testing.
> Added Config for CircleCI

- sampleData/product/product.js
- sampleData/product/productList.js
- sampleData/product/productStyles.js
- sampleData/qAndA/answers.js
- sampleData/qAndA/questions.js
- sampleData/reviews/reviewMetaData.js
- sampleData/reviews/reviewsList.js
Added sample data for all GET requests.  The endpoint used for each request is at the top.  The product is the same throughout so it should line up with what we'd see when rendering product id 1.
> Added Sample Data from Postman API Calls

- .eslintrc
- package-lock.json
- package.json
- src/components/App.js
- src/components/Product.js
- src/components/product-overview/ProductOverview.js
- src/components/question-answer/QuestionAnswer.js
- src/components/reviews/Reviews.js
- src/index.js
- src/store/reducer.js
- webpack.config.js
edited the .eslintrc file to set config options to ignore react/prop-types validation, auto-fix enabled in eslint-loader
> Tth eslint

- .circleci/config.yml
- package-lock.json
- package.json
- src/components/question-answer/QuestionAnswer.js
- src/sum.js
- test/sum.test.js
Updated CircleCI.yml
Added script for testing Jest
Added sum function file and corresponding testing file to test using Jest
> Testing Startup

- .gitignore
- dist/index.html
- dist/main.bundle.css
- package-lock.json
- package.json
- postcss.config.js
- src/components/reviews/Reviews.js
- src/components/reviews/reviews.css
- src/index.css
- src/index.js
- src/styles/tailwind.css
- tailwind.config.js
- webpack.config.js
added and configured postcss-loader, miniCssExtractPlugin to use tailwindcss and HMR for style changes.
> PostCss and Tailwind Config

- dist/main.bundle.css
- src/components/Product.js
- src/components/reviews/Reviews.js
- src/components/reviews/reviews.css
- src/components/reviews/weighted/Weighted.js
- src/components/utility/stars/Star.js
- src/components/utility/stars/StarRatings.js
- src/store/reducer.js
We were getting an "infinite loop" of requests in our Product.js component because every time fetch was being called it was setting the product in the store and the component was listening for updates on productStore ie `connect(mapStateToProps, mapDispatchToProps)(Product);` so it was causing a re-render and calling the fetch method again. I wrote a check to make sure that the route param id was different than the productStore id and then calling fetch if it is different.
> Tth reviews setup

- postcss.config.js
- sampleData/qAndA/questions.js
- src/components/question-answer/AnswerModal.js
- src/components/question-answer/Answers.js
- src/components/question-answer/Question.js
- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/QuestionModal.js
- src/components/question-answer/Questions.js
- src/components/question-answer/SearchBar.js
Framed out File Structure for QA section.
Class Components below main wrapper
Still need to work out getting global state and updating QA components with changes.
> EDT Added FileStructure for QA SubComponents

- src/components/utility/Button.js
We'll need to update this as we go but right now is set up to get passed an onClick handler as props and take props name as the text for the button.
> Added Button Utility Component

- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/SearchBar.js
Forgot to Change Branches so this is a little scattered but hardly no significant changes were made.
> Edt searchbar

- src/components/question-answer/Answers.js
- src/components/question-answer/Question.js
- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/Questions.js
- src/components/question-answer/SearchBar.js
Updated Questions and Question Component.  Pulls from API and renders each question. Styling not done yet.  Some weird formatting that the linter wanted with the text for each Question.
> Edt Questions

- src/components/product-overview/ProductOverview.js
Detailed map of component hierarchy/tree for product overview
> Jak component frameout

- src/components/reviews/Reviews.js
- src/components/reviews/list/ReviewItem.js
- src/components/utility/stars/StarRatings.js
working on displaying the review list ane finishing up display of ReviewItems
> Tth review list item

- src/components/question-answer/Answer.js
- src/components/question-answer/Answers.js
- src/components/question-answer/Question.js
- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/Questions.js
Moved API call and state storage down to Questions Component.  Decreases Passing off of State because QA is just a Container for the rest of the Subcomponents.
> Moved State and API Call From QA to Questions

- sampleData/reviews/reviewsList.js
- src/components/reviews/Reviews.js
- src/components/reviews/form/ReviewForm.js
- src/components/reviews/list/ReviewItem.js
- src/components/reviews/list/ReviewsList.js
- src/components/reviews/list/thumbnail/ReviewThumbnail.js
- src/components/utility/Modal.js
- src/store/reducer.js
@Eldamarth I added the totalReviews property to the store 
Tweaked the modal to accept both children as components and/or raw html
> Tth review form

- src/components/reviews/Reviews.js
- src/components/reviews/list/ReviewItem.js
- src/components/reviews/list/ReviewsList.js
- src/components/reviews/list/thumbnail/ReviewThumbnail.js
- src/components/utility/Modal.js
added Modal utility component that we can reuse.
Modal accepts show prop (true or false) and toggleModal (callback that sets show to false)
`<Modal show={show} toggleModal={this.toggleModal}>
{content}
</Modal>`
> Tth review thumbnails

- src/components/question-answer/QuestionAnswer.js
- src/components/utility/Button.js
Updated Some Styling to Match Reviews Styling
ButtonUtility also Updated to Match Buttons in Reviews.
> Updated Button Utility Style and Overall QA

- src/components/question-answer/Answers/Answer.js
- src/components/question-answer/Answers/Answers.js
- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/Questions/Question.js
- src/components/question-answer/Questions/Questions.js
- src/components/utility/Button.js
Changed folder structure for easier navigation. Answers now rendering based on question and API call.  Added styling for Byline to match reviews byline. Still need to work through Show More Button and more styling.
> Edt answers render

- dist/main.bundle.css
- src/components/product-overview/AddToCart.js
- src/components/product-overview/Carousel.js
- src/components/product-overview/ImageView.js
- src/components/product-overview/ProductDetails.js
- src/components/product-overview/ProductInformation.js
- src/components/product-overview/ProductOverview.css
- src/components/product-overview/ProductOverview.js
- src/components/product-overview/StyleSelector.js
Merge issues should be resolved by this.
> Jak component styling 0129

- src/components/reviews/Reviews.js
- src/components/reviews/form/ReviewForm.js
- src/components/reviews/list/ReviewItem.js
- src/components/reviews/list/ReviewsList.js
- src/components/reviews/slider/RatingSlider.js
Finished review form, ability to filter reviews based on rating, update a review to helpful/report.
> Tth review create

- src/components/product-overview/AddToCart.js
- src/components/product-overview/Carousel.js
- src/components/product-overview/ImageView.js
- src/components/product-overview/ProductOverview.js
- src/components/product-overview/StyleSelector.js
Mostly handler acrobatics with state of Overview and Add to Cart.  The Carousel ended up being on the backburner.  Handlers were a little more complicated than expected.
> Jak image carousel a2 c 0130

- src/components/question-answer/Answers/Answer.js
- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/Questions/Question.js
- src/components/question-answer/Questions/Questions.js
Added functionality for helpful and report in both Answer and Question
> Edt helpful and report

- src/components/Product.js
- src/components/question-answer/Answers/Answer.js
- src/components/question-answer/Answers/AnswerModal.js
- src/components/question-answer/Answers/Answers.js
- src/components/question-answer/Answers/CreateAnswer.js
- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/Questions/CreateQuestion.js
- src/components/question-answer/Questions/Question.js
- src/components/question-answer/Questions/QuestionModal.js
- src/components/question-answer/Questions/Questions.js
Create question working but not rendering question after creation
> Edt create question

- src/components/Product.js
- src/components/reviews/Reviews.js
working on sorting the reviews and limiting to showing 5 and show more functionality
> Tth api url

- dist/main.bundle.css
- src/components/product-overview/AddToCart.js
- src/components/product-overview/Carousel.js
- src/components/product-overview/ImageView.js
- src/components/product-overview/ProductInformation.js
- src/components/product-overview/ProductOverview.css
- src/components/product-overview/ProductOverview.js
- src/components/product-overview/StyleSelector.js
Zoom is 'working' and buttons are added.  Only L/R work, up and down aren't ready yet.
> Jak zoom 01 31

- package-lock.json
- package.json
- src/components/question-answer/Answers/Answer.js
- src/components/question-answer/Answers/AnswerModal.js
- src/components/question-answer/Answers/Answers.js
- src/components/question-answer/Answers/CreateAnswer.js
- src/components/question-answer/Answers/Photos.js
- src/components/question-answer/HelpfulReportHandler.js
- src/components/question-answer/QuestionAnswer.js
- src/components/question-answer/Questions/CreateQuestion.js
- src/components/question-answer/Questions/Question.js
- src/components/question-answer/Questions/QuestionModal.js
- src/components/question-answer/Questions/Questions.js
- src/components/question-answer/SearchBar.js
Added Tailwind classes to Components.  Rendering closer to Spec.  Some adjustments still need to be made.
> Edt qa css
